baseURL: https://www.curiosityworks.org
languageCode: en-us
title: CuriosityWorks
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy
  description:
  # navbarlogo:
  # Logo (from static/images/logos/___)
    # image: logos/fresh.svg
    # link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Learn to code
    # Hero subtitle (optional)
    subtitle: A place where kids learn to code while having fun
    # Button text
    buttontext: Next Enrollment 
    # Where the main hero button links to
    buttonlink: "/next-enrollment/"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: CuriosityWorks
    url: /
  - title: Our Mission
    url: /mission
  - title: About
    url: /about
  - title: Curriculum
    sublinks:
    - title: Python
      url: /curriculum/python
    - title: Javascript
      url: /curriculum/javascript
    - title: Lua
      url: /curriculum/lua
  # - title: Log in
  #   url: https://console.curiosityworks.org/login
  # - title: Sign up
  #   url: /post/signup/
  #   button: true
  # sidebar:
  #   # Logo (from /images/logos/___.svg)
  #   logo: fresh-square
  #   sections:
  #   - title: User
  #     icon: user
  #     links:
  #     - text: Profile
  #       url: /
  #     - text: Account
  #       url: /
  #     - text: Settings
  #       url: /
  #   - title: Messages
  #     icon: envelope
  #     links:
  #     - text: Inbox
  #       url: /
  #     - text: Compose
  #       url: /
  #   - title: Images
  #     icon: image
  #     links:
  #     - text: Library
  #       url: /
  #     - text: Upload
  #       url: /
  #   - title: Settings
  #     icon: cog
  #     links:
  #     - text: User settings
  #       url: /
  #     - text: App settings
  #       url: /
  section1:
    title: What we provide
    subtitle: to all students
    tiles:
    - title: Online Lessons
      icon: mouse-globe
      text: Fun lessons designed to keep students engaged
      url: /next-enrollment/
      buttonText: Enroll 
    - title: Online Coding Platform
      icon: laptop-cloud
      text: A browser and internet connection is all you need
      url: /next-enrollment/
      buttonText: Enroll
    - title: Online Instructor
      icon: plug-cloud
      text: Knowledgable coder who cares about teaching
      url: /next-enrollment/
      buttonText: Enroll
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Online coding courses makes sense
      text: Time saved on traveling to and from class will be reinvested in learnig. There won't be no student sitting in the back with difficulty seeing the board. Recorded lessons can be viewed later if a student misses a class.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Feedback loop
      text: We encourage students to experiment and make lots of mistakes. The teacher will provide feedback. We encourage this iteration between students and the teacher. Being afraid to make mistake is the biggest mistake one can make while learning a computer language.
      icon: doc-sync
    - title: Nomad system
      text: Students can go anywhere and use any computer to log onto CuriosityWorks online coding platform. All course work will be saved online and backed up for each student.
      icon: mobile-feed
  section3:
    title: Online Coding Platform
    subtitle: professionals use
    image: vscode.png
    buttonText: Enroll 
    buttonLink: "/next-enrollment/"
  section4:
    title: Our Students love us!
    subtitle: What students said about CuriosityWorks
    clients:
    - name: Kimberly
      quote: TBD
      job: 10th grade
      img: 1
    - name: Tommy
      quote: TBD
      job: 11th grade
      img: 2
    - name: Edward
      quote: TBD
      job: 10th grade
      img: 3
  section5: false
  footer:
    # Logo (from /images/logos/___)
    logo: lightbulb.png
    # Social Media Title
    # socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    # socialmedia:
    # - link: https://github.com/curiosinauts/
      # Icons are from Font Awesome
      # icon: github
    bulmalogo: true
    quicklinks:
      column1:
        title: "Schedule"
        links:
        - text: Next semester
          link: /next-enrollment/
      # column:
      #   title: "Docs"
      #   links:
      #   - text: Our promise
      #     link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /post/pilot_launch
